config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'dashboard', to: 'dashboards#dashboard'
  get 'dashboard/index', to: 'dashboards#index'
  post 'wishes', to: 'wishes#add'

  resources :groups, only: %i[index show new create update results] do
    resources :quizz_choices, only: %i[new create index]
    resources :movies, only: %i[index]
    resources :wishes, only: %i[create]

    member do
      post :compute_results
      get :results
    end
  end

  resources :group_users, only: %i[create update]
  resources :group_users, only: %i[edit] do
    member do
      get :movie_order
      patch :movie_order
    end
  end

  resources :friends, only: %i[index new create destroy]
  resources :movie_seens, only: %i[create index]
  resources :wishes, only: %i[index new destroy]
  resources :favorites, only: %i[index new create destroy] do
    member do
      get :friendsfav
    end
  end

  resources :quizz_choices, only: %i[edit] do
    member do
      patch :edit_genre
      patch :add_keyword
      patch :add_duration
      patch :add_date
      patch :add_actor
      patch :change_step
      patch :validate
    end
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :movie
  belongs_to :user
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = policy_scope(Favorite)
    @favorite = Favorite.new
  end

  def friendsfav
    @favorite = Favorite.new
    authorize @favorite
    @friends_list = []
    current_user.friends.map do |f|
      @friends_list << f.users_friend.id
    end

    Friend.where(users_friend_id: current_user.id).map do |f|
      @friends_list << f.user.id
    end
  end

  def create
    @movie_title = params["q"]
    @movie = Movie.where(name: @movie_title)
    @favorite = Favorite.new(user: current_user, movie: @movie.first)

    if @movie_title.empty?
      flash.alert = "You have to enter a title"
    elsif @movie.empty?
      flash.alert = "Sorry, I don't know this movie..."
    elsif Favorite.where(user: current_user, movie_id: @movie.first.id).exists?
      flash.alert = "Already in your wishlist"
    else
      flash.alert = "Added to your favorites !"
      @favorite.save!
    end
    redirect_to favorites_path
    authorize @favorite
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    authorize @favorite
    @favorite.destroy
    flash.alert = "Removed successfully!"
    redirect_to favorites_path
  end
end

app/views/favorites/friendsfav.html.erb
<% if params["user"].nil? %>

  <br><br>
  <h1 class="text-center">My friends' favorites</h1>

  <% @friends_list.each do |f| %>

      <div class="dahboard-card-content ">
        <div class="d-flex justify-content-between mb-2">
          <% user = User.where(id: f)  %>
        </div>
        <% faves = [] %>
          <% Favorite.where(user_id: user[0].id).map do |favorite| %>
            <% faves << favorite.movie %>
          <% end %>
        <% if faves.empty? %>
        <% else %>
        <div class="see-f-fav"><div><%= user[0].username %>'s favorites </div><%= link_to friendsfav_favorite_path(user: user[0].id) do %>
            <p>See all <i class="fa-solid fa-arrow-right-long"></i></p>
          <% end %>
        </div>

          <% if faves.count == 1 %>
            <div id="carouselNoTouching" class="carousel slide" data-bs-touch="true" data-bs-interval="false">
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <img src="<%= faves[0].poster %>" class="ms-3" style="height: 45%" width="45%">
                </div>
              </div>
            </div>
          <% elsif faves.count == 2 %>
            <div id="carouselNoTouching" class="carousel slide" data-bs-touch="true" data-bs-interval="false">
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <img src="<%= faves[0].poster %>" class="ms-3" style="height: 45%" width="45%">
                  <img src="<%= faves[1].poster %>" style="height: 45%" width="45%">
                </div>
            </div>
          <% elsif faves.count == 3 %>
            <div id="carouselNoTouching" class="carousel slide" data-bs-touch="true" data-bs-interval="false">
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <img src="<%= faves[0].poster %>" class="ms-3" style="height: 45%" width="45%">
                  <img src="<%= faves[1].poster %>" style="height: 45%" width="45%">
                </div>
                <div class="carousel-item">
                  <img src="<%= faves[2].poster %>" class="ms-3" style="height: 45%" width="45%">
                </div>
              <button class="carousel-control-prev" type="button" data-bs-target="#carouselNoTouching" data-bs-slide="prev">
                <%# <span class="carousel-control-prev-icon" aria-hidden="true"></span> %>
                <span class="visually-hidden">Previous</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#carouselNoTouching" data-bs-slide="next">
                <%# <span class="carousel-control-next-icon" aria-hidden="false"></span> %>
                <span class="visually-hidden">Next</span>
              </button>
            </div>
          <% elsif faves.count == 4 %>
            <div id="carouselNoTouching" class="carousel slide" data-bs-touch="true" data-bs-interval="false">
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <img src="<%= faves[0].poster %>" class="ms-3" style="height: 45%" width="45%">
                  <img src="<%= faves[1].poster %>" style="height: 45%" width="45%">
                </div>
                <div class="carousel-item">
                  <img src="<%= faves[2].poster %>" class="ms-3" style="height: 45%" width="45%">
                  <img src="<%= faves[3].poster %>" style="height: 45%" width="45%">
                </div>
              </div>
              <button class="carousel-control-prev" type="button" data-bs-target="#carouselNoTouching" data-bs-slide="prev">
                <%# <span class="carousel-control-prev-icon" aria-hidden="true"></span> %>
                <span class="visually-hidden">Previous</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#carouselNoTouching" data-bs-slide="next">
                <%# <span class="carousel-control-next-icon" aria-hidden="false"></span> %>
                <span class="visually-hidden">Next</span>
              </button>
            </div>
          <% elsif faves.count == 5 %>
            <div id="carouselNoTouching" class="carousel slide" data-bs-touch="true" data-bs-interval="false">
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <img src="<%= faves[0].poster %>" class="ms-3" style="height: 45%" width="45%">
                  <img src="<%= faves[1].poster %>" style="height: 45%" width="45%">
                </div>
                <div class="carousel-item">
                  <img src="<%= faves[2].poster %>" class="ms-3" style="height: 45%" width="45%">
                  <img src="<%= faves[3].poster %>" style="height: 45%" width="45%">
                </div>
                <div class="carousel-item">
                  <img src="<%= faves[4].poster %>" class="ms-3" style="height: 45%" width="45%">
                </div>
              </div>
              <button class="carousel-control-prev" type="button" data-bs-target="#carouselNoTouching" data-bs-slide="prev">
                <%# <span class="carousel-control-prev-icon" aria-hidden="true"></span> %>
                <span class="visually-hidden">Previous</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#carouselNoTouching" data-bs-slide="next">
                <%# <span class="carousel-control-next-icon" aria-hidden="false"></span> %>
                <span class="visually-hidden">Next</span>
              </button>
            </div>
          <% else %>
            <div id="carouselNoTouching" class="carousel slide" data-bs-touch="true" data-bs-interval="false">
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <img src="<%= faves[0].poster %>" class="ms-3" style="height: 45%" width="45%">
                  <img src="<%= faves[1].poster %>" style="height: 45%" width="45%">
                </div>
                <div class="carousel-item">
                  <img src="<%= faves[2].poster %>" class="ms-3" style="height: 45%" width="45%">
                  <img src="<%= faves[3].poster %>" style="height: 45%" width="45%">
                </div>
                <div class="carousel-item">
                  <img src="<%= faves[4].poster %>" class="ms-3" style="height: 45%" width="45%">
                  <img src="<%= faves[5].poster %>" style="height: 45%" width="45%">
                </div>
              </div>
              <button class="carousel-control-prev" type="button" data-bs-target="#carouselNoTouching" data-bs-slide="prev">
                <%# <span class="carousel-control-prev-icon" aria-hidden="true"></span> %>
                <span class="visually-hidden">Previous</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#carouselNoTouching" data-bs-slide="next">
                <%# <span class="carousel-control-next-icon" aria-hidden="false"></span> %>
                <span class="visually-hidden">Next</span>
              </button>
            </div>
            <% end %>
          <% end %>
      </div>

  <% end %>

<% else %>

  <h5><%= User.where(id: params["user"]).first.username %>'s favorites</h5>

  <% favorites = [] %>
  <% Favorite.where(user_id: params["user"]).map { |f| favorites << f.movie_id } %>

  <div class="movie-container">
    <% favorites.each do |id| %>
      <button type="button" class="card-movie background" id = "dragitem"
              data-drag-target="card" data-movie-id="<%= Movie.where(id: id)[0].id %>"
              data-bs-toggle="modal" data-bs-target="#filmsModal<%=Movie.where(id: id)[0].id%>" >
        <img src="<%= Movie.where(id: id)[0].poster %>" width="10%" />
        <div class="card-movie-infos">
          <h2 class="text-start overflow-visible"><%= Movie.where(id: id)[0].name %></h2>
          <p class="text-start genres-infos">
            <%= Movie.where(id: id)[0].genre[0...4].to_s.gsub(/[\[\]\"]/,"") %>
          </p>
          <p class="text-start other-infos"><%= Movie.where(id: id)[0].year %>  ~  <%= Movie.where(id: id)[0].duration %> min  ~  <%= Movie.where(id: id)[0].rating %>/10 <i class="fa-solid fa-star"></i></p>
        </div>
      </button>
    <% end %>
  </div>

  <div>
    <%# Modals %>
    <% favorites.each do |id| %>
      <div class="modal fade" id="filmsModal<%=Movie.where(id: id)[0].id%>" tabindex="-1" aria-labelledby="filmsModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
          <div class="modal-content bg-dark">

            <div class="modal-body">
              <img src= "<%= Movie.where(id: id)[0].poster %>" class="final-poster" object-fit="cover" style="border-radius: 10px"/>
              <div class="card-movie-infos">
                <h2 class="mt-4"><strong><%= Movie.where(id: id)[0].name %></strong></h2>
                <div>
                  <p class="text-start"><%= Movie.where(id: id)[0].genre.to_s.gsub(/[\[\]\"]/,"") %></p>
                  <p><%= Movie.where(id: id)[0].year %> - <%= Movie.where(id: id)[0].duration %> min</p>
                </div>

                <hr>

                <div>
                  <p class="fw-semibold text-decoration-underline fs-6 wish-show-small-titles">Casting</p>
                  <p><%= Movie.where(id: id)[0].actor.first(3).to_s.gsub(/[\[\]\"]/,"") %></p>
                </div>

                <hr>

                <div>
                  <p class="fw-semibold text-decoration-underline fs-6 wish-show-small-titles">Synopsis</p>
                  <p class="synopsis"><%= Movie.where(id: id)[0].synopsis %></p>
                </div>

                <hr>
                <div>
                <% if Movie.where(id: id)[0].platform? == true %>
                    <p class="fw-semibold text-decoration-underline fs-6 wish-show-small-titles">Available on</p>
                    <p><%= Movie.where(id: id)[0].platform.to_s.gsub(/[\[\]\"]/,"") %></p>
                  <% else %>
                    <small>This movie is not free on any platform</small>
                  <% end %>
                </div>
              </div>
            </div>

            <div class="modal-footer">
              <div class="d-flex justify-content-between w-100">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              </div>
            </div>

          </div>
        </div>
      </div>
    <% end%>
    <br><br><br>
  </div>

<% end %>

app/views/favorites/index.html.erb
<%# ------------------------ Searchbar for adding ----------------------- %>

<h3 class="my-4">Add a favorite</h3>

<%= form_tag(favorites_path, method: 'post', class: "form-inline") do %>
  <div data-controller="autocomplete" class="form-search search-data" data-autocomplete-choices-value="<%= Movie.all.pluck(:name) %>">
    <%= text_field_tag :q, nil, autocomplete: :off, class: "form-control search-input", placeholder: "Search a movie...", data: { "autocomplete-target": "searchInput" } %>
  <br>
  </div>
    <div class="abs-pos">
      <%= submit_tag "Add", class: "bottom-button" %>
    </div>
<% end %>


<br>
<h1 class="text-center">My favorites</h1>


<%# ------------------------ Display of current favorites ------------------------ %>

<% movies = [] %>
  <% Favorite.where(user_id: current_user.id).each do |favorite| %>
    <% movies << favorite.movie_id %>
<% end %>

<% if movies.empty? %>

  <br>
  <p style="text-align: center"><%= "You have no favorites yet" %></p>

<% else %>

  <div class="movie-container">
    <% movies.each do |id| %>
      <button type="button" class="card-movie background" id = "dragitem"
              data-drag-target="card" data-movie-id="<%= Movie.where(id: id)[0].id %>"
              data-bs-toggle="modal" data-bs-target="#filmsModal<%=Movie.where(id: id)[0].id%>" >
        <img src="<%= Movie.where(id: id)[0].poster %>" width="10%" />
        <div class="card-movie-infos">
          <h2 class="text-start overflow-visible"><%= Movie.where(id: id)[0].name %></h2>
          <p class="text-start genres-infos">
            <%= Movie.where(id: id)[0].genre[0...4].to_s.gsub(/[\[\]\"]/,"") %>
          </p>
          <p class="text-start other-infos"><%= Movie.where(id: id)[0].year %>  ~  <%= Movie.where(id: id)[0].duration %> min  ~  <%= Movie.where(id: id)[0].rating %>/10 <i class="fa-solid fa-star"></i></p>
        </div>
      </button>
    <% end %>
  </div>

<% end %>

<br><br>

<div>
  <%# Modals %>
  <% movies.each do |id| %>
    <div class="modal fade" id="filmsModal<%=Movie.where(id: id)[0].id%>" tabindex="-1" aria-labelledby="filmsModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content bg-dark">

          <div class="modal-body">
            <img src= "<%= Movie.where(id: id)[0].poster %>" class="final-poster" object-fit="cover" style="border-radius: 10px"/>
            <div class="card-movie-infos">
              <h2 class="mt-4"><strong><%= Movie.where(id: id)[0].name %></strong></h2>
              <div>
                <p class="text-start"><%= Movie.where(id: id)[0].genre.to_s.gsub(/[\[\]\"]/,"") %></p>
                <p><%= Movie.where(id: id)[0].year %> - <%= Movie.where(id: id)[0].duration %> min</p>
              </div>

              <hr>

              <div>
                <p class="fw-semibold text-decoration-underline fs-6 wish-show-small-titles">Casting</p>
                <p><%= Movie.where(id: id)[0].actor.first(3).to_s.gsub(/[\[\]\"]/,"") %></p>
              </div>

              <hr>

              <div>
                <p class="fw-semibold text-decoration-underline fs-6 wish-show-small-titles">Synopsis</p>
                <p class="synopsis"><%= Movie.where(id: id)[0].synopsis %></p>
              </div>

              <hr>
              <div>
              <% if Movie.where(id: id)[0].platform? == true %>
                  <p class="fw-semibold text-decoration-underline fs-6 wish-show-small-titles">Available on</p>
                  <p><%= Movie.where(id: id)[0].platform.to_s.gsub(/[\[\]\"]/,"") %></p>
                <% else %>
                  <small>This movie is not free on any platform</small>
                <% end %>
              </div>
              <div class="modal-footer">
                <div class="d-flex justify-content-between w-100">
                  <p class="m-0">
                    <%= link_to favorite_path(Favorite.where(user_id: current_user).where(movie_id: id)[0]), data: {turbo_method: "delete"} do %>
                      <i class='fa-solid fa-trash-can m-0 trash'></i>
                    <% end %>
                  </p>
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  <% end%>
  <br><br>
</div>

app/views/favorites/new.html.erb
<h1>Favorites#new</h1>
<p>Find me in app/views/favorites/new.html.erb</p>