config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'dashboard', to: 'dashboards#dashboard'
  get 'dashboard/index', to: 'dashboards#index'
  post 'wishes', to: 'wishes#add'

  resources :groups, only: %i[index show new create update results] do
    resources :quizz_choices, only: %i[new create index]
    resources :movies, only: %i[index]
    resources :wishes, only: %i[create]

    member do
      post :compute_results
      get :results
    end
  end

  resources :group_users, only: %i[create update]
  resources :group_users, only: %i[edit] do
    member do
      get :movie_order
      patch :movie_order
    end
  end

  resources :friends, only: %i[index new create destroy]
  resources :movie_seens, only: %i[create index]
  resources :wishes, only: %i[index new destroy]
  resources :favorites, only: %i[index new create destroy] do
    member do
      get :friendsfav
    end
  end

  resources :quizz_choices, only: %i[edit] do
    member do
      patch :edit_genre
      patch :add_keyword
      patch :add_duration
      patch :add_date
      patch :add_actor
      patch :change_step
      patch :validate
    end
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @group = Group.find(params["group_id"])
    @group.points_to_achieve = @group.group_users.count * 15
    @group.save

    @movies = policy_scope(Movie)
    @genre_all, @keyword_all, @duration_all, @date_all, @actor_all = Array.new(5) { [] }

    Group.find(params["group_id"]).quizz_choices.each do |q|
      @genre_all << q.genre
      @keyword_all << q.keyword
      @duration_all << q.duration
      @date_all << [q.start_year, q.end_year]
      @actor_all << q.actor
    end

    @movies_max = []

    Movie.all.each do |m|
      @genre_all.flatten.each do |g|
        @movies_max << m if m.genre.include?(g)
      end

      @keyword_all.flatten.each do |k|
        @movies_max << m if m.keyword.include?(k)
      end

      @duration_all.flatten.each do |d|
        @movies_max << m if m.duration <= d
      end

      @date_all.each do |date|
        @movies_max << m if (m.year >= date[0] && m.year <= date[1])
      end

      @actor_all.flatten.each do |a|
        @movies_max << m if m.actor.include?(a)
      end
    end

    @movies = @movies_max.tally.max_by(5) { |key, value| value }.map { |a| a[0] }

    # movie_popular = movie_finder.tally
    # @movies = movie_popular.max_by(6) { |_key, value| value }.map { |a| a[0] }.reject { |m| m.nil? }

    if (@group.points_to_achieve - @group.total_points) <= 1
      redirect_to results_group_path(@group)
    end
  end
end

app/views/movies/create.html.erb
<h1>Movies#create</h1>
<p>Find me in app/views/movies/create.html.erb</p>

app/views/movies/edit.html.erb
<h1>Movies#edit</h1>
<p>Find me in app/views/movies/edit.html.erb</p>

app/views/movies/index.html.erb
<% if params[:wait_for_the_others] == "true" %>

  <div class="text-center">
    <br><br><br><h6>Wait for the others...</h6>
    <br>
    <div class="spinner-border text-warning" style="width: 3rem; height: 3rem;" role="status">
      <span class="visually-hidden">Loading...</span>
    </div>
  </div>

  <script>
    setTimeout(function() {
      location.reload();
    }, 5000);
  </script>

<% else %>

  <div class="progress progress-index-top my-4">
    <div class="progress-bar" role="progressbar" style="width: 95%;" aria-valuenow="95" aria-valuemin="0" aria-valuemax="100"></div>
  </div>

  <h1 class="title">Order your movies</h1>
  <% n = 0 %>
  <% base_poster_url = "https://image.tmdb.org/t/p/original" %>
  <br>

  <div class="movie-container" id="draglist" data-controller = "drag">
    <% @movies.compact.each do |m| %>
      <button type="button" class="card-movie background" id = "dragitem"
              data-drag-target="card" data-movie-id="<%= m.id %>"
              data-bs-toggle="modal" data-bs-target="#filmsModal<%=m.id%>" >
        <img src="<%= m.poster %>" width="10%" />
        <div class="card-movie-infos">
          <h2 class="text-start overflow-visible"><%= m.name %></h2>
          <p class="text-start">
            <%= m.genre[0...4].to_s.gsub(/[\[\]\"]/,"") %>
          </p>
          <p class="text-start"><%= m.year %> ~ <%= m.duration %> min ~ <%= m.rating %>/10 <i class="fa-solid fa-star"></i></p>
        </div>
      </button>
    <% end %>

    <%= simple_form_for :ordered_choice, url: compute_results_group_path(@group), data: {turbo_method: "post"} do |f|%>
      <%= f.input :movie_order, input_html: {data: {drag_target: "input"}, type: "hidden", value: @movies.pluck(:id)}, label: false%>
      <div style="margin-bottom:92px;"></div>
      <%= f.submit "Vote!", class: "bottom-button"%>
    <% end %>
  </div>


  <div>
    <%# Modals %>
    <% @movies.each do |m| %>
      <div class="modal fade" id="filmsModal<%=m.id%>" tabindex="-1" aria-labelledby="filmsModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
          <div class="modal-content bg-dark">

            <div class="modal-body">
              <img src= "<%= m.poster %>" class="final-poster" object-fit="cover" style="border-radius: 10px" />
              <div class="card-movie-infos">
                <h2 class="mt-4"><strong><%= m.name %></strong></h2>
                <div>
                  <p class="text-start"><%= m.genre.to_s.gsub(/[\[\]\"]/,"") %></p>
                  <p><%= m.year %> - <%= m.duration %> min.</p>
                </div>

                <hr>

                <div>
                  <p class="fw-semibold text-decoration-underline fs-6 wish-show-small-titles">Casting</p>
                  <p><%= m.actor.first(3).to_s.gsub(/[\[\]\"]/,"") %></p>
                </div>

                <hr>

                <div>
                  <p class="fw-semibold text-decoration-underline fs-6 wish-show-small-titles">Synopsis</p>
                  <p><%= m.synopsis %></p>
                </div>

                <hr>
                <div>
                  <% if m.platform? == true %>
                    <p class="fw-semibold text-decoration-underline fs-6">Available on</p>
                    <p><%= m.platform.to_s.gsub(/[\[\]\"]/,"") %></p>
                  <% else %>
                    <small>This movie is not free on any platform</small>
                  <% end %>
                </div>
              </div>
            </div>

              <% if Wish.where(user_id: current_user.id).map do |n| n.movie_id end.include?(m.id) %>
              <hr style="margin-top: 0">
              <div class="modal-footer-one justify-content-between">
                <%= link_to wish_path(Wish.where(user_id: current_user.id).where(movie_id: m.id)[0]), data: {turbo_method: 'delete'} do %>
                  <i class="fa fa-heart" style="font-size: 24px" aria-hidden="true"></i>
                <% end %>
              <% else %>
              <hr style="margin-top: 0">
              <div class="modal-footer-two justify-content-between">
                <%= link_to group_wishes_path(@group, wish: { movie_id: m.id }), data: {turbo_method: 'post'} do %>
                  <i class="fa fa-heart" style="font-size: 24px" aria-hidden="true"></i>
                <% end %>
              <% end %>
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>

          </div>
        </div>
      </div>
    <% end%>
  </div>

<% end %>

app/views/movies/new.html.erb
<h1>Movies#new</h1>
<p>Find me in app/views/movies/new.html.erb</p>