config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'dashboard', to: 'dashboards#dashboard'
  get 'dashboard/index', to: 'dashboards#index'
  post 'wishes', to: 'wishes#add'

  resources :groups, only: %i[index show new create update results] do
    resources :quizz_choices, only: %i[new create index]
    resources :movies, only: %i[index]
    resources :wishes, only: %i[create]

    member do
      post :compute_results
      get :results
    end
  end

  resources :group_users, only: %i[create update]
  resources :group_users, only: %i[edit] do
    member do
      get :movie_order
      patch :movie_order
    end
  end

  resources :friends, only: %i[index new create destroy]
  resources :movie_seens, only: %i[create index]
  resources :wishes, only: %i[index new destroy]
  resources :favorites, only: %i[index new create destroy] do
    member do
      get :friendsfav
    end
  end

  resources :quizz_choices, only: %i[edit] do
    member do
      patch :edit_genre
      patch :add_keyword
      patch :add_duration
      patch :add_date
      patch :add_actor
      patch :change_step
      patch :validate
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :ordered_choices
  has_many :group_users
  has_many :quizz_choices
  has_many :users, through: :group_users
  validates :name, presence: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :update, :compute_results, :results]

  def index
    @groups = policy_scope(Group)
  end

  def show
    authorize @group
    if !OrderedChoice.where(group: @group).empty?
      @final = find_result
    end
  end

  def new
    @solo = params[:solo]
    @group = Group.new
    authorize @group
    @group_user = GroupUser.new
    @friends = []
    @friends << current_user.friends.map(&:users_friend)
    @friends << Friend.where(users_friend: current_user).map(&:user)
    @friends.flatten!
  end

  def create
    @group = Group.new(params_group)
    @group.user = current_user
    authorize @group
    @friends = []
    @friends << current_user.friends.map(&:users_friend)
    @friends << Friend.where(users_friend: current_user).map(&:user)
    @friends.flatten!
    if params["group"]["user_id"]
      if (params["group"]["user_id"].count > 0) && @group.save
        @user_ids = params[:group][:user_id]
        @user_ids.each do |id|
          group_user = GroupUser.new(user_id: id, group_id: @group.id)
          group_user.save
        end
        group_user = GroupUser.new(user_id: current_user.id, group_id: @group.id)
        group_user.save
        redirect_to group_path(@group)
      else
        render :new
      end
    else
      if @group.save
        group_user = GroupUser.new(user_id: current_user.id, group_id: @group.id)
        group_user.save
        redirect_to group_path(@group)
      else
        render :new
      end
    end
  end

  def update
    authorize @group
    @group.update(archive: true)
    redirect_to groups_path, status: :see_other
  end

  def compute_results
    if params["ordered_choice"]["movie_order"].split(',').length == 1
      @ids = params["ordered_choice"]["movie_order"].split(' ')
    else
      @ids = params["ordered_choice"]["movie_order"].split(',')
    end
    authorize @group
    @points = [5, 4, 3, 2, 1]
    @ids.each do |movie_id|
      if OrderedChoice.find_by(movie: Movie.find(movie_id.to_i), group: @group)
        oc = OrderedChoice.find_by(movie: Movie.find(movie_id.to_i), group: @group)
        oc.update(point: oc.point += @points[@ids.index(movie_id)])
      else
        OrderedChoice.create(movie: Movie.find(movie_id.to_i), group: @group, point: @points[@ids.index(movie_id)])
      end
    end
    h = {}
    OrderedChoice.where(group: @group).each do |oc|
      h[oc.movie_id] = oc.point
    end
    @final = Movie.find(h.sort_by {|k, v| v}.reverse.first.first)

    @group.total_points = OrderedChoice.where(group: @group).sum(:point)
    # @group.points_to_achieve = @group.group_users.count * 15
    @group.save

    if (@group.points_to_achieve - @group.total_points) > 1
      redirect_to group_movies_path(@group, wait_for_the_others: true)
    else
      redirect_to results_group_path(@group)
    end
  end

  def results
    authorize @group
    @final = find_result
  end

  private

  def find_result
    h = {}
    OrderedChoice.where(group: @group).each do |oc|
      h[oc.movie_id] = oc.point
    end
    return Movie.find(h.sort_by {|k, v| v}.reverse.first.first)
  end

  def set_group
    @group = Group.find(params[:id])
  end

  def params_group
    params.require(:group).permit(:name)
  end
end

app/views/groups/index.html.erb
<div style="margin-bottom: 100px;">
  <div class="row d-flex text-center">
    <h1 class="dash-text mb-4">Your games</h1>
  </div>

  <div class="text-center mx-3">
    <% @groups.each do |group| %>
      <%= link_to group_path(group.id), class:'add-group' do %>
        <p><%= group.name %></p>
      <% end %>
    <% end %>
  </div>
</div>
<%= link_to "New game", new_group_path(solo: false), class:'bottom-button' %>

app/views/groups/new.html.erb
<div class="create-group">

  <h1>New game</h1>

  <%= simple_form_for @group do |f| %>
    <%= f.input :name, placeholder: 'Give a name to your session..', label: false%>
    <% if @solo == "false" %>
    <br>
    <p>&nbsp;&nbsp;&nbsp;Who do you want to play with?</p>
      <%= f.association :user, collection: @friends, as: :check_boxes, label_method: :username %>
    <% end %>
    <%= f.submit "Let's start !", class:"bottom-button" %>
  <% end %>

</div>

app/views/groups/results.html.erb
<div class="title">
  <h1>Here it is!</h1>
</div>

<% n = 0 %>

<div class="modal-body">

  <div class="margin-auto">
    <div class="lotti-bg">
      <lottie-player src="https://assets9.lottiefiles.com/packages/lf20_tiviyc3p.json"  background="transparent" speed="1" loop autoplay></lottie-player>
    </div>
    <img src= "<%= @final.poster %>" class="final-poster" object-fit="cover" style="border-radius: 10px" />
  </div>
  <div class="card-movie-infos mt-4">
    <h2 class="mt-4"><strong><%= @final.name %></strong></h2>
    <div>
      <p><%= @final.genre.to_s.gsub(/[\[\]\"]/,"") %></p>
      <p><%= @final.year %> - <%= @final.duration %> min.</p>
    </div>

    <hr>

    <div>
      <p class="fw-semibold text-decoration-underline fs-6 wish-show-small-titles">Casting</p>
      <p class="final-text-align"><%= @final.actor.first(3).to_s.gsub(/[\[\]\"]/,"") %></p>
    </div>

    <hr>

    <div>
      <p class="fw-semibold text-decoration-underline fs-6 wish-show-small-titles">Synopsis</p>
      <p class="final-text-align"><%= @final.synopsis %></p>
    </div>

    <hr>
    <div>
      <% if @final.platform? == true %>
        <p class="fw-semibold text-decoration-underline fs-6 final-text-align wish-show-small-titles">Available on</p>
        <p><%= @final.platform.to_s.gsub(/[\[\]\"]/,"") %></p>
      <% else %>
        <small class="final-text-align">This movie is not free on any platform</small>
      <% end %>
    </div>
  </div>

</div>

app/views/groups/show.html.erb
<div class="row d-flex">
  <h1 class="text-center fw-bold my-4 group-name"><%= @group.name %></h1>
</div>


  <div class="text-center ">

    <% if @final %>

      <div class="member-content">
        <p>This session is over</p>
        <h4 class="my-4 member-title">Who played?</h4>
          <% @group.users.each do |user| %>
          <div class="d-flex justify-content-center align-items-center member">
            <i class="fa-solid fa-user-tie mx-2"></i>
            <p class="member-group"><%= user[:username] %> </p>
          </div>
        <% end %>
      </div>

      <h4 class="my-4 member-title">What was the final movie?</h4>

      <div>
        <div class="bg-dark">
          <div class="modal-body">
            <img src= "<%= @final.poster %>" class="final-poster" object-fit="cover" style="border-radius: 10px" />
            <div class="card-movie-infos">
              <h2 class="mt-4"><strong><%= @final.name %></strong></h2>
              <div>
                <p class="text-start"><%= @final.genre.to_s.gsub(/[\[\]\"]/,"") %></p>
                <p><%= @final.year %> - <%= @final.duration %> min.</p>
              </div>

              <hr>

              <div>
                <p class="fw-semibold text-decoration-underline fs-6">Casting</p>
                <p><%= @final.actor.first(3).to_s.gsub(/[\[\]\"]/,"") %></p>
              </div>

              <hr>

              <div>
                <p class="fw-semibold text-decoration-underline fs-6">Synopsis</p>
                <p><%= @final.synopsis %></p>
              </div>

              <hr>
              <div>
                <% if @final.platform == "true" %>
                  <p class="fw-semibold text-decoration-underline fs-6">Available on</p>
                  <p><%= @final.platform.to_s.gsub(/[\[\]\"]/,"") %></p>
                <% else %>
                  <small>This movie is not free on any platform</small>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% else %>

      <div class="member-content">
        <h4 class="my-4 member-title">Who's playing ?</h4>
          <% @group.users.each do |user| %>
          <div class="d-flex justify-content-center align-items-center member">
            <i class="fa-solid fa-user-tie mx-2"></i>
            <p class="member-group"><%= user[:username] %> </p>
          </div>
        <% end %>
      </div>

      <%= link_to "Start the quiz", new_group_quizz_choice_path(@group), class: "bottom-button" %>

    <% end %>



    <%# if @group.quizz_choices.where(user_id: current_user.id).first.nil? || @group.quizz_choices.where(user_id: current_user.id).first.sent == false %>
    <%# end %>
    <div class="delete-groups">
      <%= link_to "Delete", group_path(@group.id), data: {turbo_method: "patch"}, class: 'delete-group' %>
    </div>
  </div>
<br>