config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'dashboard', to: 'dashboards#dashboard'
  get 'dashboard/index', to: 'dashboards#index'
  post 'wishes', to: 'wishes#add'

  resources :groups, only: %i[index show new create update results] do
    resources :quizz_choices, only: %i[new create index]
    resources :movies, only: %i[index]
    resources :wishes, only: %i[create]

    member do
      post :compute_results
      get :results
    end
  end

  resources :group_users, only: %i[create update]
  resources :group_users, only: %i[edit] do
    member do
      get :movie_order
      patch :movie_order
    end
  end

  resources :friends, only: %i[index new create destroy]
  resources :movie_seens, only: %i[create index]
  resources :wishes, only: %i[index new destroy]
  resources :favorites, only: %i[index new create destroy] do
    member do
      get :friendsfav
    end
  end

  resources :quizz_choices, only: %i[edit] do
    member do
      patch :edit_genre
      patch :add_keyword
      patch :add_duration
      patch :add_date
      patch :add_actor
      patch :change_step
      patch :validate
    end
  end
end

app/models/quizz_choice.rb
class QuizzChoice < ApplicationRecord
  belongs_to :group
  belongs_to :user
  serialize :genre, Array
end

app/controllers/quizz_choices_controller.rb
require 'open-uri'

class QuizzChoicesController < ApplicationController
  before_action :find_quizz_choice, only: %i[edit edit_genre add_keyword add_duration add_date add_actor change_step]
  before_action :actor_list_params, only: %i[index edit]
  before_action :keyword_list_params, only: %i[index]

  def new
    @group = Group.find(params[:group_id])
    @quizz_choice = QuizzChoice.new
    authorize @quizz_choice
  end

  def create
    @quizz_choice = QuizzChoice.new(quizz_choice_params)
    @quizz_choice.group = Group.find(params[:group_id])
    @quizz_choice.user = current_user
    @quizz_choice.genre = params["quizz_choice"]["genre"].reject(&:empty?)
    authorize @quizz_choice
    if @quizz_choice.save
      redirect_to edit_quizz_choice_path(@quizz_choice)
    else
      render :new
    end
  end

  def index
    @quizz_choices = policy_scope(QuizzChoice)
    @group = Group.find(params[:group_id])
    @quizz_choice = current_user.quizz_choices.where(group: @group).first
    @nb_of_users = Group.find(params[:group_id]).users.count
    @nb_of_quizz_submitted = Group.find(params[:group_id]).quizz_choices.where(sent: true).count
    redirect_to group_movies_path if @nb_of_users == @nb_of_quizz_submitted
  end

  def edit
    authorize @quizz_choice
    keyword_list_params if @quizz_choice.step == "add_date"
  end

  def change_step
    @quizz_choice = QuizzChoice.find(params[:id])
    @group = @quizz_choice.group
    authorize @quizz_choice
    if @quizz_choice.step.strip == 'initial'
      @quizz_choice.destroy
      redirect_to new_group_quizz_choice_path(@group), status: :see_other
    else
      @old_step = @quizz_choice.step
      case @quizz_choice.step
      when "add_keyword"
        @quizz_choice.step = "initial"
      when "add_duration"
        @quizz_choice.step = "add_keyword"
      when "add_date"
        @quizz_choice.step = "add_duration"
      when "add_actor"
        @quizz_choice.step = "add_date"
      end
      @quizz_choice.save!
      @new_step = @quizz_choice.step
      redirect_to edit_quizz_choice_path(@quizz_choice), status: :see_other
    end
  end

  def edit_genre
    authorize @quizz_choice
    @quizz_choice.genre = params["quizz_choice"]["genre"].reject(&:empty?)
    @quizz_choice.update(quizz_choice_params)
    @quizz_choice.step = "edit_genre"
    @quizz_choice.save!
    redirect_to group_quizz_choices_path(@quizz_choice.group)
  end

  def add_keyword
    authorize @quizz_choice
    @quizz_choice.keyword = params["q"]
    @quizz_choice.step = "add_keyword"
    @quizz_choice.save!
    if params[:edit] == "true"
      redirect_to group_quizz_choices_path(@quizz_choice.group)
    else
      redirect_to edit_quizz_choice_path(@quizz_choice)
    end
  end

  def add_duration
    authorize @quizz_choice
    @quizz_choice.duration = params["quizz_choice"]["duration"]
    @quizz_choice.step = "add_duration"
    @quizz_choice.save!
    if params[:edit] == "true"
      redirect_to group_quizz_choices_path(@quizz_choice.group)
    else
      redirect_to edit_quizz_choice_path(@quizz_choice)
    end
  end

  def add_date
    authorize @quizz_choice
    @quizz_choice.update(quizz_choice_params)
    @quizz_choice.step = "add_date"
    @quizz_choice.save!
    if params[:edit] == "true"
      redirect_to group_quizz_choices_path(@quizz_choice.group)
    else
      redirect_to edit_quizz_choice_path(@quizz_choice)
    end
  end

  def add_actor
    authorize @quizz_choice
    @quizz_choice.actor = params["q"]
    @quizz_choice.step = "add_actor"
    @quizz_choice.save!
    redirect_to group_quizz_choices_path(@quizz_choice.group)
    # **********
    # LA OU LA MAGIE OPERE
  end

  def validate
    @quizz_choice = QuizzChoice.where(user_id: current_user.id).find(params[:id])
    authorize @quizz_choice
    @quizz_choice.sent = true
    @quizz_choice.save
    redirect_to group_quizz_choices_path(@quizz_choice.group)
  end

  private

  def find_quizz_choice
    # authorize @quizz_choice
    @quizz_choice = QuizzChoice.find(params[:id])
  end

  def quizz_choice_params
    params.require(:quizz_choice).permit(:genre, :duration, :actor, :keyword, :start_year, :end_year)
  end

  def actor_list_params
    @actor_list = Actor.pluck(:name)
  end

  def keyword_list_params
    @keywords_list = Movie.pluck(:keyword).flatten.uniq.to_json
  end
end

# @quizz_choice = QuizzChoice.new( ... , step: "initial")

app/views/quizz_choices/_actor.html.erb
<div class="progress progress-edit-top my-4">
  <div class="progress-bar" role="progressbar" style="width: 65%;" aria-valuenow="65" aria-valuemin="0" aria-valuemax="100"></div>
</div>

<br>

<h3 class="my-5">Is there an actor you would like to see?</h3>

<%= form_tag(add_actor_quizz_choice_path(@quizz_choice), method: 'patch', class: "form-inline") do %>
  <div data-controller="autocomplete" class="form-search search-data" data-autocomplete-choices-value="<%= @actor_list.to_json %>">
    <%= text_field_tag :q, nil, autocomplete: :off, class: "form-control search-input", placeholder: "Search an actor...", data: { "autocomplete-target": "searchInput" } %>
  </div>

    <%= submit_tag "You're almost done!", class: "bottom-button" %>
<% end %>

<br><br>
<p class="p-index" style="padding: 0 20px"><em>Ex: Johnny Depp, Natalie Portman, Miles Teller, Maggie Smith, Omar Sy ...</em> </p>

app/views/quizz_choices/_casting.html.erb
<div class="container">

  <div class="progress">
    <div class="progress-bar" role="progressbar" style="width: 75%;" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">75%</div>
  </div>

  <input type="text" id="search">
  <ul id="results">
      <li>Actor 1 :</li>
      <li>Actor 2 :</li>
    </ul>

<% (1...2).each do |page_number|  %>
  <% actors = JSON.parse(URI.open("https://api.themoviedb.org/3/person/popular?api_key=5a07d55b0507c919cb598bae7c6fd7b4&page=#{page_number}").read)["results"] %>
  <% actor_list = [] %>
  <% actors.each do |act| %>
    <% actor_list << act['name'] %>
  <% end %>
<% end %>

<%= actor_list %>


<%#= form_tag(root_path, method: 'get', class: "form-inline") do %>
  <div id= "search-data" class="form-search search-data" data-skills="<%= @skills.to_json %>">
    <%#= text_field_tag :q, nil, autocomplete: :off, class: "form-control search-input", placeholder: "Search by programming language..." %>
    <%#= submit_tag "Search", class: "btn btn-primary button-home" %>
  </div>
<%# end %>

</div>

app/views/quizz_choices/_date.html.erb
<div class="progress progress-edit-top my-4">
  <div class="progress-bar" role="progressbar" style="width: 45%;" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100"></div>
</div>

<br>

<h3 class="my-5">Choose a period</h3>

<%= simple_form_for @quizz_choice, url: add_date_quizz_choice_path(@quizz_choice), method: :patch do |f| %>
  <div class="d-flex justify-content-center w-100 fs-1">
    <%= f.select :start_year, options_for_select(1960..2022, 1960), { prompt: "start year" }, class: 'date-year border-end' %>
    <%= f.select :end_year, options_for_select(1960..2022, 2022), { prompt: "end date" }, class: 'date-year' %>


    <% if edit %>
      <%= hidden_field_tag :edit, "true" %>
    <% end %>

    <%= f.submit "Next", class: "bottom-button" %>
  </div>
<% end %>

app/views/quizz_choices/_duration.html.erb
<div class="progress progress-edit-top my-4">
  <div class="progress-bar" role="progressbar" style="width: 30%;" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"></div>
</div>

<br>

<h3 class="my-5">How much time do you have?</h3>

<%= simple_form_for @quizz_choice, url: add_duration_quizz_choice_path(@quizz_choice), method: :patch do |f| %>
  <div class="rangeslider">
    <%= f.input :duration,
                as: :range,
                input_html: {
                  min: 20,
                  max: 260,
                  value: 150,
                  step: 30,
                  class: 'myslider',
                  id: 'sliderRange',
                },
                label: false %>
    <p class="text-center"><span id="demo"></span> min</p>


    <% if edit %>
      <%= hidden_field_tag :edit, "true" %>
    <% end %>

    <%= f.submit "Next", class: "bottom-button" %>
  </div>
<% end %>

<script>
  var rangeslider = document.getElementById("sliderRange");
  var duration = document.getElementById("demo");

  duration.innerHTML = rangeslider.value;

  rangeslider.oninput = function() {
    duration.innerHTML = this.value;
  }
</script>

app/views/quizz_choices/_edit_genre.html.erb
<h3 class="my-4">Choose a genre</h3>

<%= simple_form_for [@group, @quizz_choice], url: edit_genre_quizz_choice_path(@quizz_choice), method: :patch do |f| %>

  <%= f.input :genre, as: :check_boxes,
              collection: ["Adventure", "Action", "Animation", "Comedy", "Romance",
                            "Crime", "Drama", "Fantasy", "Family", "History", "Horror", "Music",
                            "Mystery", "Thriller", "TV Movie", "War", "Western", "Documentary", "Science Fiction"],
              label: "" %>
  <%= f.submit "Next", class: "bottom-button"  %>

<% end %>

app/views/quizz_choices/_genre_edit.html.erb
<h3 class="my-4">Choose a genre</h3>

<%= simple_form_for [@group, @quizz_choice], url: add_genre_quizz_choice_path(@quizz_choice), method: :patch do |f| %>
  <%= f.input :genre, as: :check_boxes, collection: ["Action", "Adventure", "Animation","Comedy","Crime","Documentary","Drama","Fantasy","Family","History","Horror","Music","Mystery","Romance","Science Fiction","Thriller", "TV Movie", "War", "Western"], class: "checkbox"  %>
  <%= f.button :submit, class: "bottom-button"  %>
<% end %>

app/views/quizz_choices/_keyword.html.erb
<div class="progress progress-edit-top my-4">
  <div class="progress-bar" role="progressbar" style="width: 15%;" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"></div>
</div>

<br>

<h3 class="my-5">Any wish ?</h3>

<%= form_tag(add_keyword_quizz_choice_path(@quizz_choice), method: 'patch', class: "form-inline") do %>
  <div class="form-search search-data" data-autocomplete-choices-value="<%= @keywords_list %> " data-controller="autocomplete">
    <%= text_field_tag :q, nil, autocomplete: :off, class: "form-control search-input", placeholder: "Search a keyword...", data: { "autocomplete-target": "searchInput" } %>
  </div>

  <% if edit %>
    <%= hidden_field_tag :edit, "true" %>
  <% end %>

  <%= submit_tag "Next", class: "bottom-button" %>
<% end %>

<br><br>
<p class="p-index" style="padding: 0 20px"><em>Ex: cowboy, love, ninja, italy, investigation, murder, witch, superhero ...</em> </p>

app/views/quizz_choices/edit.html.erb
<%= link_to "", change_step_quizz_choice_path, data: { 'turbo-method': :patch } , class:"fa-solid fa-angle-left fa-2x arrow edit-navbar link-none" %>

<% if @quizz_choice.step == "initial" %>
  <%= render "duration", edit: false %>
<% elsif @quizz_choice.step == "add_duration" %>
  <%= render "date", edit: false %>
<% elsif @quizz_choice.step == "add_date" %>
  <%= render "keyword", edit: false %>
<% else @quizz_choice.step == "add_keyword" %>
  <%= render "actor", edit: false %>
<% end %>

app/views/quizz_choices/index.html.erb
<div class="progress progress-index-top my-4">
  <div class="progress-bar" role="progressbar" style="width: 80%;" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
</div>

<div class="summary my-2">

  <div class="row">
    <h1 class="text-center my-4 font-weight-bold">Your answers</h1>

    <br>

    <hr>

    <div>
      <div class="text-center mx-3">
        <button type="button" class="recap" data-bs-toggle="modal" data-bs-target="#genreModal">
          <% if @quizz_choice.genre? == true %>
            <h5><%= @quizz_choice.genre.flatten.to_s.gsub(/[\[\]\"]/,"") %></h5>
          <% else %>
            <small><em> Select a genre </em></small>
          <% end %>
        </button>
      </div>

      <div class="modal fade" id="genreModal" tabindex="-1"
           aria-labelledby="genreModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-fullscreen">
          <div class="modal-content bg-dark">

            <div class="modal-header">
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
              <%= render 'edit_genre'%>
            </div>

          </div>
        </div>
      </div>
    </div>


    <div>
      <div class="text-center mx-3">
        <button type="button" class="recap" data-bs-toggle="modal" data-bs-target="#durationModal">
          <h5><%= @quizz_choice.duration %> min</h5>
        </button>
      </div>

      <div class="modal fade" id="durationModal" tabindex="-1"
           aria-labelledby="durationModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-fullscreen">
          <div class="modal-content bg-dark">

            <div class="modal-header">
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
              <%= render 'duration', edit: true %>
            </div>

          </div>
        </div>
      </div>
    </div>

    <div>
      <div class="text-center mx-3">
        <button type="button" class="recap" data-bs-toggle="modal" data-bs-target="#dateModal">
          <h5><%= @quizz_choice.start_year %> - <%= @quizz_choice.end_year %></h5>
        </button>
      </div>

      <div class="modal fade" id="dateModal" tabindex="-1"
           aria-labelledby="dateModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-fullscreen">
          <div class="modal-content bg-dark">

            <div class="modal-header">
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
              <%= render 'date', edit: true %>
            </div>

          </div>
        </div>
      </div>
    </div>

    <div>
      <div class="text-center mx-3">
        <button type="button" class="recap" data-bs-toggle="modal" data-bs-target="#keywordModal">
          <% if @quizz_choice.keyword? == true %>
            <h5><%= @quizz_choice.keyword.capitalize %></h5>
          <% else %>
            <small><em> Select a keyword </em></small>
          <% end %>
        </button>
      </div>

      <div class="modal fade" id="keywordModal" tabindex="-1"
            aria-labelledby="keywordModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-fullscreen">
          <div class="modal-content bg-dark">

            <div class="modal-header">
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
              <%= render 'keyword', edit: true %>
            </div>

          </div>
        </div>
      </div>
    </div>

    <div>
      <div class="text-center mx-3">
        <button type="button" class="recap" data-bs-toggle="modal" data-bs-target="#actorModal">
          <% if @quizz_choice.actor? == true %>
            <h5><%= @quizz_choice.actor %></h5>
          <% else %>
            <span><small><em> Select an actor </em></small></span>
          <% end %>
        </button>
      </div>

      <div class="modal fade" id="actorModal" tabindex="-1"
           aria-labelledby="actorModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-fullscreen">
          <div class="modal-content bg-dark">

            <div class="modal-header">
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
              <%= render 'actor' %>
            </div>

        </div>
      </div>

    </div>

  </div>

  <div class="bottom-button">
    <% if @quizz_choice.sent? %>
      <p>Wait for the others...</p>
      <script>
        setTimeout(function() {
          location.reload();
        }, 5000);
      </script>
    <% else %>
      <%= link_to "Let the magic begin!", validate_quizz_choice_path(@quizz_choice), data: { turbo_method: :patch } %>
    <% end %>
  </div>

</div>

app/views/quizz_choices/new.html.erb
<div class="progress progress-new-top my-4">
  <div class="progress-bar" role="progressbar" style="width: 5%;" aria-valuenow="5" aria-valuemin="0" aria-valuemax="100"></div>
</div>

<h3 class="my-3">Let's choose a genre</h3>

<%= simple_form_for [@group, @quizz_choice] do |f| %>

  <%= f.input :genre, as: :check_boxes,
              collection: ["Action", "Adventure", "Animation", "Comedy", "Crime",
                          "Documentary", "Drama", "Family", "Fantasy", "History", "Horror", "Music",
                          "Mystery", "Romance", "Thriller", "TV Movie", "War", "Western", "Science Fiction"], label: "" %>
  <div style="margin-bottom:92px;"></div>

  <%= f.submit "Next", class: "bottom-button" %>

<% end %>